#!/usr/bin/env python3
"""Shared hierarchy node definitions for full-automation (single unified queue)."""

from __future__ import annotations

# Second-level expand nodes — all branches in one ordered list (A→J + meta).
EXPAND_NODES: list[dict] = [
    {"id": "INTRO", "title": "Executive summary and north star (§0–§1)", "source_section": "§0–§1", "branch": "meta"},
    {"id": "MASTER", "title": "Master hierarchy top level (§2 branches A–J)", "source_section": "§2", "branch": "meta"},
    # A — Pursuit & control
    {"id": "A1", "title": "Goal model", "source_section": "§3", "parent": "A", "branch": "A"},
    {"id": "A2", "title": "Pursuit loop (always-on)", "source_section": "§3", "parent": "A", "branch": "A"},
    {"id": "A3", "title": "Autopilot modes", "source_section": "§3", "parent": "A", "branch": "A"},
    {"id": "A4", "title": "Stop reasons (exhaustive taxonomy)", "source_section": "§3", "parent": "A", "branch": "A"},
    {"id": "A5", "title": "Continue semantics (redefined)", "source_section": "§3", "parent": "A", "branch": "A"},
    {"id": "A6", "title": "Notification (not blocking)", "source_section": "§3", "parent": "A", "branch": "A"},
    # B — Cognition & routing
    {"id": "B1", "title": "Capability classes (S0–S4)", "source_section": "§4", "parent": "B", "branch": "B"},
    {"id": "B2", "title": "Role model (conductor + workers)", "source_section": "§4", "parent": "B", "branch": "B"},
    {"id": "B3", "title": "Model policy", "source_section": "§4", "parent": "B", "branch": "B"},
    {"id": "B4", "title": "Dual-stack cognition (every turn)", "source_section": "§4", "parent": "B", "branch": "B"},
    {"id": "B5", "title": "Company role switching (template-pack)", "source_section": "§4", "parent": "B", "branch": "B"},
    {"id": "B6", "title": "Workflow composer routing (transistors)", "source_section": "§19", "parent": "B", "branch": "B"},
    # C — Product execution
    {"id": "C1", "title": "Pipeline registry", "source_section": "§5", "parent": "C", "branch": "C"},
    {"id": "C2", "title": "Phase chain (composable)", "source_section": "§5", "parent": "C", "branch": "C"},
    {"id": "C3", "title": "Task system", "source_section": "§5", "parent": "C", "branch": "C"},
    {"id": "C4", "title": "Program / parallel execution", "source_section": "§5", "parent": "C", "branch": "C"},
    {"id": "C5", "title": "Feature & app delivery", "source_section": "§5", "parent": "C", "branch": "C"},
    {"id": "C6", "title": "Generator workflow execution (transistors)", "source_section": "§19", "parent": "C", "branch": "C"},
    # D — Platform evolution
    {"id": "D1", "title": "Promotion ladder (reuse maturity)", "source_section": "§6", "parent": "D", "branch": "D"},
    {"id": "D2", "title": "Platform queue", "source_section": "§6", "parent": "D", "branch": "D"},
    {"id": "D3", "title": "Scheduling policy (parallel product and self-improvement)", "source_section": "§6", "parent": "D", "branch": "D"},
    {"id": "D4", "title": "Platform work types", "source_section": "§6", "parent": "D", "branch": "D"},
    {"id": "D5", "title": "Extend vs fork vs configure", "source_section": "§6", "parent": "D", "branch": "D"},
    {"id": "D6", "title": "Platform definition of done", "source_section": "§6", "parent": "D", "branch": "D"},
    # E — Knowledge & composition
    {"id": "E1", "title": "Catalog (single discovery surface)", "source_section": "§7", "parent": "E", "branch": "E"},
    {"id": "E2", "title": "Composition protocol (mandatory before S1+)", "source_section": "§7", "parent": "E", "branch": "E"},
    {"id": "E3", "title": "Facts & decisions", "source_section": "§7", "parent": "E", "branch": "E"},
    {"id": "E4", "title": "Context retrieval layers", "source_section": "§7", "parent": "E", "branch": "E"},
    {"id": "E5", "title": "Staleness & traceability", "source_section": "§7", "parent": "E", "branch": "E"},
    {"id": "E6", "title": "Transistor registry", "source_section": "§19", "parent": "E", "branch": "E"},
    {"id": "E7", "title": "Generator workflow composition", "source_section": "§19", "parent": "E", "branch": "E"},
    # F — Organization
    {"id": "F1", "title": "Pack structure (target schema)", "source_section": "§8", "parent": "F", "branch": "F"},
    {"id": "F2", "title": "Company instantiation", "source_section": "§8", "parent": "F", "branch": "F"},
    {"id": "F3", "title": "Example: game studio pack", "source_section": "§8", "parent": "F", "branch": "F"},
    {"id": "F4", "title": "Example: data platform pack", "source_section": "§8", "parent": "F", "branch": "F"},
    {"id": "F5", "title": "Cross-pack composition", "source_section": "§8", "parent": "F", "branch": "F"},
    {"id": "F6", "title": "Role → agent mapping", "source_section": "§8", "parent": "F", "branch": "F"},
    # G — Verification
    {"id": "G1", "title": "Evidence gates (existing)", "source_section": "§9", "parent": "G", "branch": "G"},
    {"id": "G2", "title": "Goal-level verification (NEW)", "source_section": "§9", "parent": "G", "branch": "G"},
    {"id": "G3", "title": "Conformance & workflow", "source_section": "§9", "parent": "G", "branch": "G"},
    {"id": "G4", "title": "Review triggers (automated)", "source_section": "§9", "parent": "G", "branch": "G"},
    {"id": "G5", "title": "Mistake class → control mapping", "source_section": "§9", "parent": "G", "branch": "G"},
    {"id": "G6", "title": "Rollback & recovery", "source_section": "§9", "parent": "G", "branch": "G"},
    # H — Persistence
    {"id": "H1", "title": "journal/state.json (v2 additive fields)", "source_section": "§10", "parent": "H", "branch": "H"},
    # I — Runtime
    {"id": "I1", "title": "In-IDE (Cursor)", "source_section": "§11", "parent": "I", "branch": "I"},
    {"id": "I2", "title": "Local SDK daemon", "source_section": "§11", "parent": "I", "branch": "I"},
    {"id": "I3", "title": "Headless / scheduled", "source_section": "§11", "parent": "I", "branch": "I"},
    {"id": "I4", "title": "External tools (per pack)", "source_section": "§11", "parent": "I", "branch": "I"},
    {"id": "I5", "title": "Notifications", "source_section": "§11", "parent": "I", "branch": "I"},
    # Meta sections
    {"id": "SEC-15", "title": "Implementation roadmap v2.14–v2.28", "source_section": "§15", "branch": "meta"},
    {"id": "SEC-18", "title": "Transistor model A–Z reference", "source_section": "§19", "branch": "meta"},
    {"id": "SEC-17", "title": "Open design decisions", "source_section": "§17", "branch": "meta"},
    {"id": "APP-A", "title": "Full human job taxonomy", "source_section": "§18", "branch": "meta"},
]

# Pre-identified document leaves (no further expand) under H, J, SEC, APP
STANDALONE_DOCUMENTS: list[dict] = [
    {"id": "H2", "title": "journal/progress.md — human mirror", "source_section": "§10", "parent": "H", "branch": "H",
     "output": "documents/plans/full-automation/H2-journal-progress.md"},
    {"id": "H3", "title": "Artifact graphs", "source_section": "§10", "parent": "H", "branch": "H",
     "output": "documents/plans/full-automation/H3-artifact-graphs.md"},
    {"id": "H4", "title": "evidence/ immutable logs", "source_section": "§10", "parent": "H", "branch": "H",
     "output": "documents/plans/full-automation/H4-evidence.md"},
    {"id": "H5", "title": "worker-runs.jsonl audit", "source_section": "§10", "parent": "H", "branch": "H",
     "output": "documents/plans/full-automation/H5-worker-runs.md"},
    {"id": "H6", "title": "Snapshots preCompact sync-state", "source_section": "§10", "parent": "H", "branch": "H",
     "output": "documents/plans/full-automation/H6-snapshots.md"},
    {"id": "J1", "title": "model-policy.json", "source_section": "§12", "parent": "J", "branch": "J",
     "output": "documents/plans/full-automation/J1-model-policy.md"},
    {"id": "J2", "title": "automation-waivers.md", "source_section": "§12", "parent": "J", "branch": "J",
     "output": "documents/plans/full-automation/J2-automation-waivers.md"},
    {"id": "J3", "title": "strict_hitl mode flag", "source_section": "§12", "parent": "J", "branch": "J",
     "output": "documents/plans/full-automation/J3-strict-hitl.md"},
    {"id": "J4", "title": "audit trail", "source_section": "§12", "parent": "J", "branch": "J",
     "output": "documents/plans/full-automation/J4-audit.md"},
    {"id": "J5", "title": "export-contract", "source_section": "§12", "parent": "J", "branch": "J",
     "output": "documents/plans/full-automation/J5-export-contract.md"},
    {"id": "J6", "title": "release-queue.json harness evolution", "source_section": "§12", "parent": "J", "branch": "J",
     "output": "documents/plans/full-automation/J6-release-queue.md"},
    {"id": "SEC-13", "title": "End-to-end pursuit flow", "source_section": "§13", "branch": "meta",
     "output": "documents/plans/full-automation/SEC-13-pursuit-flow.md"},
    {"id": "SEC-14", "title": "Gap analysis today → target", "source_section": "§14", "branch": "meta",
     "output": "documents/plans/full-automation/SEC-14-gap-analysis.md"},
    {"id": "APP-B", "title": "state.json sketch (additive)", "source_section": "§19", "branch": "meta",
     "output": "documents/plans/full-automation/APP-B-state-json-sketch.md"},
]

LEAVES: dict[str, str] = {
    "INTRO-0": "Executive summary (§0)",
    "INTRO-1.1": "100% automation scope in/out",
    "INTRO-1.2": "Human touchpoint contract H1 H2 H3",
    "INTRO-1.3": "Goal completion criterion",
    "INTRO-2": "Transistor building blocks north star",
    "MASTER-A": "Branch A — Pursuit & control plane",
    "MASTER-B": "Branch B — Cognition & routing plane",
    "MASTER-C": "Branch C — Product execution plane",
    "MASTER-D": "Branch D — Platform evolution plane",
    "MASTER-E": "Branch E — Knowledge & composition plane",
    "MASTER-F": "Branch F — Organization plane",
    "MASTER-G": "Branch G — Verification & quality plane",
    "MASTER-H": "Branch H — Persistence & state plane",
    "MASTER-I": "Branch I — Runtime & integration plane",
    "MASTER-J": "Branch J — Governance & operator plane",
    "A1.1": "goal_id parent_goal goal_type",
    "A1.2": "success_criteria machine-checkable",
    "A1.3": "goal_verify_command meta-test",
    "A1.4": "deadline budget steps tokens wall clock",
    "A1.5": "goal_state enum pursuing blocked verifying achieved rejected",
    "A2.1": "preflight check-pipeline-blocked extended",
    "A2.2": "if READY execute one pipeline step",
    "A2.3": "post-step route-tier dual-write increment",
    "A2.4": "goal_scope_complete run goal_verify",
    "A2.5": "goal_verify pass transition H3 pending",
    "A2.6": "loop until blocked budget achieved H3 reject",
    "A2.7": "no intermediate wait for continue",
    "A3.1": "session_autopilot max_steps_per_session",
    "A3.2": "goal_autopilot until goal_verify or hard block",
    "A3.3": "company_autopilot multi-goal role workstreams",
    "A3.4": "sdk_daemon run-local-pipeline 24/7",
    "A4.1": "stop human H1 H2 H3",
    "A4.2": "stop verify evidence goal_verify regression",
    "A4.3": "stop resource max_steps max_cost lease_expired",
    "A4.4": "stop integrity validate-workflow state corrupt",
    "A4.5": "stop completion goal achieved program done",
    "A5.1": "continue resume pursuit if not blocked",
    "A5.2": "continue not approval self-gate H1 H3 only",
    "A5.3": "default after H1 auto-enter goal_autopilot",
    "A6.1": "notify dashboard STATUS webhook phase complete",
    "A6.2": "notify digest on H2 blocker not every step",
    "A6.3": "operator observe without unblocking loop",
    "B1.1": "S0 deterministic mandatory first",
    "B1.2": "S1 mechanical economy workers catalog",
    "B1.3": "S2 templated artifacts",
    "B1.4": "S3 architecture ambiguity",
    "B1.5": "S4 governance escalation H2 packaging",
    "B2.1": "Conductor genius merge route platform drain",
    "B2.2": "Librarian allowed_reads catalog composition",
    "B2.3": "Phase workers implement design explore",
    "B2.4": "Verifier tool-operator evidence",
    "B2.5": "Reviewer bugbot security risk triggers",
    "B2.6": "Platform worker promotion queue parallel slot",
    "B3.1": "genius orchestration only thin turns",
    "B3.2": "economy bulk code search shell",
    "B3.3": "escalation loop on verify fail",
    "B3.4": "platform turns economy plus S0 scripts",
    "B4.1": "PRODUCT next_action task each turn",
    "B4.2": "PLATFORM promotion_queue peek drain",
    "B4.3": "compose-first catalog before improvise",
    "B4.4": "divergence log when not composing",
    "B5.1": "active_role from template pack",
    "B5.2": "role to pipeline_id skills tool permissions",
    "B5.3": "handoff manifest artifact graph",
    "B5.4": "conductor stays workers swap role context",
    "B6.1": "workflow-composer skill S3 graph planning",
    "B6.2": "conductor approves generator workflow at H1",
    "B6.3": "one workflow node per product turn default",
    "B6.4": "gate transistor pass fail edge routing",
    "C1.1": "pipeline software-greenfield",
    "C1.2": "pipeline iterative_feature",
    "C1.3": "pipeline multi-domain-program",
    "C1.4": "pack-defined pipelines per company template",
    "C2.1": "phase spec-parser requirements",
    "C2.2": "phase hld dd diagrams",
    "C2.3": "phase task-breakdown scaffold implement",
    "C2.4": "phase test refactor git-workflow",
    "C2.5": "phase inputs outputs verify catalog refs",
    "C3.1": "task cards Components Promotion note",
    "C3.2": "work orders parallel lanes",
    "C3.3": "evidence per task",
    "C3.4": "task to goal rollup percent goal_verify",
    "C4.1": "workstreams lane.json leases",
    "C4.2": "orchestrate-program",
    "C4.3": "integration manifest cross-stream contract",
    "C4.4": "artifact-graph per program and pack",
    "C5.1": "src tests e2e delivery",
    "C5.2": "environment setup tasks ordered first",
    "C5.3": "definition of done goal slice satisfied",
    "C6.1": "phase workflow-compose mandatory before implement",
    "C6.2": "workflow DAG artifact schema JSON",
    "C6.3": "task card binds workflow_node_id",
    "C6.4": "parallel workflow branches via work orders",
    "C6.5": "workflow node rollup to goal_verify",
    "D1.1": "L0 ephemeral one-off reasoning",
    "D1.2": "L1 playbook docs/playbooks",
    "D1.3": "L2 script S0 scripts/",
    "D1.4": "L3 skill command cursor skills",
    "D1.5": "L4 ambient hooks CI scheduled",
    "D1.6": "L5 template-pack fragment",
    "D1.7": "L6 transistor registered composable block",
    "D2.1.1": "enqueue repeated manual command 2x",
    "D2.1.2": "enqueue worker flags repetition",
    "D2.1.3": "enqueue verify pattern N task cards",
    "D2.1.4": "enqueue conductor post-mortem escalation",
    "D2.1.5": "enqueue compose miss missing transistor",
    "D2.2": "platform queue item schema",
    "D2.3": "dequeue platform turn not product",
    "D3.1": "1 platform turn per K product turns",
    "D3.2": "priority boost queue depth threshold",
    "D3.3": "priority cut product blocked missing tool",
    "D3.4": "idle drain product waits H2",
    "D3.5": "max platform backlog age force drain",
    "D4.1": "platform work playbook-keeper",
    "D4.2": "platform work script extraction",
    "D4.3": "platform work skill command wrapper",
    "D4.4": "platform work hook validate-workflow",
    "D4.5": "platform work catalog regeneration",
    "D4.6": "platform work pack fragment export",
    "D4.7": "platform work transistor extraction",
    "D5.1": "configure task-level params only",
    "D5.2": "extend backwards-compatible staleness bump",
    "D5.3": "fork new catalog entry provenance",
    "D6.1": "platform done catalog INDEX row",
    "D6.2": "platform done verify script L2+",
    "D6.3": "platform done task card references",
    "D6.4": "platform done staleness node wired",
    "D6.5": "platform done transistor registry and graph",
    "E1.1": "catalog scripts manifest generated",
    "E1.2": "catalog playbooks INDEX",
    "E1.3": "catalog skills index",
    "E1.4": "catalog facts INDEX",
    "E1.5": "catalog pipelines manifest",
    "E1.6": "catalog template-packs README",
    "E1.7": "catalog platform CATALOG.md umbrella",
    "E2.1": "compose resolve capability needed",
    "E2.2": "compose query catalog list-components",
    "E2.3": "compose rank script playbook skill facts",
    "E2.4": "compose plan task card Components",
    "E2.5": "compose miss L0 enqueue promotion",
    "E3.1": "facts docs/facts external truth",
    "E3.2": "decisions docs/decisions ADR",
    "E3.3": "remember skill INDEX no FTS global",
    "E4.1": "context always-on rules AGENTS.md",
    "E4.2": "context hooks inject continue start",
    "E4.3": "context allowed_reads cap max 5",
    "E5.1": "staleness design graph staleness.json",
    "E5.2": "staleness extend playbooks scripts pack nodes",
    "E5.3": "staleness reconcile-stale artifact-graph skills",
    "E5.4": "staleness workflow graph transistor nodes",
    "E6.1": "catalog transistors manifest registry",
    "E6.2": "transistor schema id version typed io",
    "E6.3": "transistor classes hard soft gate",
    "E6.4": "list-transistors query io compatibility",
    "E6.5": "compose rank hard transistor script soft",
    "E7.1": "resolve deliverable type workflow template",
    "E7.2": "stitch transistors into generator DAG",
    "E7.3": "validate wiring preconditions postconditions S0",
    "E7.4": "workflow miss enqueue transistor promotion",
    "E7.5": "pack generator workflow templates inherit",
    "F1.1": "pack company.yaml schema",
    "F1.2": "pack roles/*.yaml",
    "F1.3": "pack pipelines/*.yaml",
    "F1.4": "pack manifest.md integration contracts",
    "F1.5": "pack artifact-graph.json cross-role",
    "F1.6": "pack playbooks role-specific",
    "F1.7": "pack template tasks seed cards",
    "F1.8": "pack verify goal_verify suites",
    "F1.9": "pack transistors and generator workflows",
    "F2.1": "company instantiate program-scoper pack select",
    "F2.2": "company spawn workstream department role lane",
    "F2.3": "company active_role rotates ready work",
    "F2.4": "company conductor handoffs manifest graph",
    "F3.1": "game studio roles designer TA animator programmer QA build release",
    "F3.2": "game studio pipelines concept to build",
    "F3.3": "game studio external tools Blender UE Git CI",
    "F3.4": "game studio goal_verify asset engine tests perf",
    "F4.1": "data platform roles analyst engineer DBA SRE governance",
    "F4.2": "data platform pipelines ingest model deploy monitor",
    "F5.1": "cross-pack imports micro-packs",
    "F5.2": "template-packs _shared library",
    "F5.3": "no repo outside template-packs ceiling",
    "F5.4": "shared transistors library template-packs _shared",
    "F6.1": "role mapping conductor context switch active_role",
    "F6.2": "role allowed_reads scoped playbooks lane tasks",
    "F6.3": "role tool permissions MCP CLI allowlist",
    "F6.4": "role evidence requirements per output type",
    "G1.1": "task verify-router verifier",
    "G1.2": "evidence_required state",
    "G1.3": "last_verify before advance",
    "G2.1": "goal_verify_command state pack",
    "G2.2": "goal_verify aggregates unit integration e2e tool",
    "G2.3": "goal_verify blocks H3 until pass",
    "G2.4": "goal_verify regression every implement batch",
    "G2.5": "per-node evidence rollup goal_verify",
    "G3.1": "conformance validate-workflow CI",
    "G3.2": "conformance route-tier check",
    "G3.3": "conformance check-pipeline-blocked goal_autopilot",
    "G4.1": "review security-review touch paths deps",
    "G4.2": "review bugbot large diffs",
    "G4.3": "review escalation S4 repeated verify fail",
    "G4.4": "review staleness reconciliation before merge",
    "G5.1": "mistake hallucinated done evidence gate",
    "G5.2": "mistake scope creep allowed_reads task card",
    "G5.3": "mistake wrong architecture self-gate goal_verify",
    "G5.4": "mistake skipped tests verify-router mandatory",
    "G5.5": "mistake stale design staleness reconcile",
    "G5.6": "mistake duplicate tooling platform queue catalog",
    "G5.7": "mistake unsafe command preToolUse allowlist",
    "G5.8": "mistake fuzzy chain lost in prose workflow control",
    "G6.1": "rollback git branch per goal slice",
    "G6.2": "rollback journal last_failure structured H2",
    "G6.3": "rollback autopilot resume preCompact snapshot",
    "G6.4": "workflow checkpoint replay from failed node",
    "H1.1": "state existing next_action program autopilot evidence tier",
    "H1.2": "state goal block",
    "H1.3": "state platform block",
    "H1.4": "state pursuit block",
    "H1.5": "state hitl block",
    "H1.6": "state company block",
    "H1.7": "state active_workflow block",
    "I1.1": "runtime IDE genius conductor session",
    "I1.2": "runtime IDE local subagents economy",
    "I1.3": "runtime IDE slash commands autopilot continue lane verify",
    "I1.4": "runtime IDE hooks beforeSubmit subagentStart preToolUse preCompact",
    "I2.1": "runtime SDK run-local-pipeline goal_autopilot",
    "I2.2": "runtime SDK CURSOR_API_KEY AUTOPILOT_MODEL",
    "I2.3": "runtime SDK operator PC worker server",
    "I3.1": "runtime headless headless-verify",
    "I3.2": "runtime headless GitHub Actions validate verify",
    "I3.3": "runtime headless pull-ready complete-work-order lanes",
    "I4.1": "runtime external MCP browser DCC cloud",
    "I4.2": "runtime external tool-operator Tool command task cards",
    "I4.3": "runtime external evidence-types non-pytest",
    "I4.4": "transistor executors MCP tool script boundary",
    "I5.1": "runtime notify STATUS dashboard generation",
    "I5.2": "runtime notify webhook email H2 H3 only",
    "SEC-15-v2.14": "Release v2.14 goal model goal_verify",
    "SEC-15-v2.15": "Release v2.15 pursuit loop goal_autopilot self-gate",
    "SEC-15-v2.16": "Release v2.16 platform queue scheduler",
    "SEC-15-v2.17": "Release v2.17 catalog compose-first list-components",
    "SEC-15-v2.18": "Release v2.18 staleness graph platform nodes",
    "SEC-15-v2.19": "Release v2.19 company pack schema active_role",
    "SEC-15-v2.20": "Release v2.20 game studio pack reference",
    "SEC-15-v2.21": "Release v2.21 data platform pack reference",
    "SEC-15-v2.22": "Release v2.22 cross-pack _shared library",
    "SEC-15-v2.23": "Release v2.23 operator polish H2 audit dashboard",
    "SEC-15-v2.24": "Release v2.24 transistor schema registry list-transistors",
    "SEC-15-v2.25": "Release v2.25 workflow DAG validate-workflow-dag",
    "SEC-15-v2.26": "Release v2.26 workflow-composer active_workflow execution",
    "SEC-15-v2.27": "Release v2.27 pack workflow templates cross-domain",
    "SEC-15-v2.28": "Release v2.28 transistor maturity dashboard metrics",
    "SEC-17-1": "Decision self-gate rigor checklist vs reviewer",
    "SEC-17-2": "Decision H3 scope task milestone release company",
    "SEC-17-3": "Decision platform K ratio fixed vs adaptive",
    "SEC-17-4": "Decision budget caps unlimited vs checkpoint",
    "SEC-17-5": "Decision pack authority legal finance H2-always",
    "SEC-17-6": "Decision multi-goal single stack vs company_autopilot",
    "SEC-17-7": "Decision transistor granularity one verify boundary",
    "SEC-17-8": "Decision composer S3 skill not conductor inline",
    "SEC-17-9": "Decision JSON DAG authoritative visual editor optional",
    "SEC-17-10": "Decision global _shared transistors plus pack overlay",
    "SEC-18": "Transistor model A to Z reference",
    "APP-A-discover": "Work taxonomy discover and plan",
    "APP-A-design": "Work taxonomy design",
    "APP-A-build": "Work taxonomy build",
    "APP-A-verify": "Work taxonomy verify",
    "APP-A-release": "Work taxonomy release and operate",
    "APP-A-organize": "Work taxonomy organize company",
    "APP-A-improve": "Work taxonomy improve platform",
}


def slug(text: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-")[:60]


def parent_id(item_id: str) -> str | None:
    if item_id.startswith("INTRO-"):
        return "INTRO"
    if item_id.startswith("MASTER-"):
        return "MASTER"
    if item_id.startswith("SEC-15-"):
        return "SEC-15"
    if item_id.startswith("SEC-17-"):
        return "SEC-17"
    if item_id.startswith("APP-A-"):
        return "APP-A"
    parts = item_id.split(".")
    if len(parts) <= 1:
        return None
    return ".".join(parts[:-1])


def leaves_for_parent(parent: str) -> list[tuple[str, str]]:
    """Return (id, title) leaves whose parent_id matches parent, sorted."""
    out = [(lid, title) for lid, title in LEAVES.items() if parent_id(lid) == parent]
    return sorted(out, key=lambda x: x[0])
